# Site settings
title: Average Joe
description: "Everything youâ€™ve ever wanted to know about coffeehouses in Singapore."
url: "https://averagejoe.reviews"

# Author
author:
  name: Chester How
  url: https://chester.how
  email: chesterhow@gmail.com
  github_username: chesterhow

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Permalinks
permalink: /:year-:month-:day/:title

# Post excerpt
excerpt_separator: <!--more-->

# Pagination
pagination:
  enabled: true
  debug: true
  per_page: 7
  sort_reverse: true
  title: ':title'
  permalink: '/page/:num/'
